In [3]:
import numpy as np

In [142]:
def max_element(arr):
    l = len(arr)
    print (l)
    print (arr)
    print (arr == 0)
    zero_pos = np.where(arr == 0)
    no_zero_pos = np.where(arr != 0)
    print (zero_pos)
    a = np.array(zero_pos)
    for elem in zero_pos:
            elem = (elem + 1)
            e = np.array(elem)
            l1 = len(e)
            maxe = max(e)
            print (maxe)
            ind_max = np.where(e == maxe)
            print (ind_max)
            if maxe > l:
                e1 = np.delete(e, ind_max)
                print (e1)
    print (e1)
    

In [143]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [144]:
print (max_element(x))

9
[6 2 0 3 0 0 5 7 0]
[False False  True False  True  True False False  True]
(array([2, 4, 5, 8]),)
9
(array([3]),)


UnboundLocalError: local variable 'e1' referenced before assignment